name: build-and-deploy
on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Clone Repository
              uses: actions/checkout@v2

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'

            - name: Restore dotnet tools
              run: dotnet tool restore

            - name: Run Build
              run: dotnet docfx ./source/docfx.json

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: artifacts/_site
                clean: true
